import psycopg2

exchange_data = [{"name":"bithumb","display_name":"Bithumb"},
    {"name":"bitfinex","display_name":"Bitfinex"},
    {"name":"bittrex","display_name":"Bittrex"},
    {"name":"binance","display_name":"Binance"},
    {"name":"gdax","display_name":"GDAX"},
    {"name":"poloniex","display_name":"Poloniex"},
    {"name":"okex","display_name":"OKEx"},
    {"name":"bitstamp","display_name":"Bitstamp"},
    {"name":"huobi","display_name":"Huobi"},
    {"name":"hitbtc","display_name":"HitBTC"},
    {"name":"coinone","display_name":"Coinone"},
    {"name":"kraken","display_name":"Kraken"},
    {"name":"btcc","display_name":"BTCC"},
    {"name":"korbit","display_name":"Korbit"},
    {"name":"bitflyer","display_name":"bitFlyer"},
    {"name":"gemini","display_name":"Gemini"},
    {"name":"lakebtc","display_name":"LakeBTC"},
    {"name":"coinnest","display_name":"Coinnest"},
    {"name":"zb-com","display_name":"ZB.COM"},
    {"name":"bit-z","display_name":"Bit-Z"},
    {"name":"exmo","display_name":"Exmo"},
    {"name":"coinsbank","display_name":"CoinsBank"},
    {"name":"exx","display_name":"EXX"},
    {"name":"wex","display_name":"WEX"},
    {"name":"cex-io","display_name":"CEX.IO"},
    {"name":"gate-io","display_name":"Gate.io"},
    {"name":"liqui","display_name":"Liqui"},
    {"name":"yobit","display_name":"YoBit"},
    {"name":"bitcoin-indonesia","display_name":"Bitcoin Indonesia"},
    {"name":"bits-blockchain","display_name":"Bits Blockchain"},
    {"name":"btc-markets","display_name":"BTC Markets"},
    {"name":"bitbay","display_name":"BitBay"},
    {"name":"livecoin","display_name":"Livecoin"},
    {"name":"cryptopia","display_name":"Cryptopia"},
    {"name":"tidex","display_name":"Tidex"},
    {"name":"mercado-bitcoin","display_name":"Mercado Bitcoin"},
    {"name":"zaif","display_name":"Zaif"},
    {"name":"koinex","display_name":"Koinex"},
    {"name":"getbtc","display_name":"GetBTC"},
    {"name":"bcc-exchange","display_name":"BCC Exchange"},
    {"name":"bx-thailand","display_name":"BX Thailand"},
    {"name":"aex","display_name":"AEX"},
    {"name":"paribu","display_name":"Paribu"},
    {"name":"itbit","display_name":"itBit"},
    {"name":"quadrigacx","display_name":"QuadrigaCX"},
    {"name":"bitbank","display_name":"Bitbank"},
    {"name":"rightbtc","display_name":"RightBTC"},
    {"name":"bitso","display_name":"Bitso"},
    {"name":"dsx","display_name":"DSX"},
    {"name":"coinegg","display_name":"CoinEgg"},
    {"name":"luno","display_name":"Luno"},
    {"name":"coolcoin","display_name":"CoolCoin"},
    {"name":"btcturk","display_name":"BTCTurk"},
    {"name":"foxbit","display_name":"Foxbit"},
    {"name":"quoine","display_name":"Quoine"},
    {"name":"neraex","display_name":"Neraex"},
    {"name":"xbtce","display_name":"xBTCe"},
    {"name":"gatecoin","display_name":"Gatecoin"},
    {"name":"coinexchange","display_name":"CoinExchange"},
    {"name":"etherdelta","display_name":"EtherDelta"},
    {"name":"bitshares-asset-exchange","display_name":"BitShares Asset Exchange"},
    {"name":"coinfloor","display_name":"Coinfloor"},
    {"name":"exrates","display_name":"Exrates"},
    {"name":"bigone","display_name":"BigONE"},
    {"name":"gatehub","display_name":"Gatehub"},
    {"name":"coinfalcon","display_name":"CoinFalcon"},
    {"name":"koinim","display_name":"Koinim"},
    {"name":"okcoin-intl","display_name":"OkCoin Intl."},
    {"name":"allcoin","display_name":"Allcoin"},
    {"name":"coinsquare","display_name":"Coinsquare"},
    {"name":"negocie-coins","display_name":"Negocie Coins"},
    {"name":"litebit","display_name":"LiteBit.eu"},
    {"name":"bitonic","display_name":"Bitonic"},
    {"name":"bitmarket","display_name":"BitMarket"},
    {"name":"bl3p","display_name":"BL3P"},
    {"name":"independent-reserve","display_name":"Independent Reserve"},
    {"name":"topbtc","display_name":"TOPBTC"},
    {"name":"mercatox","display_name":"Mercatox"},
    {"name":"kucoin","display_name":"Kucoin"},
    {"name":"ripplefox","display_name":"RippleFox"},
    {"name":"btc-alpha","display_name":"BTC-Alpha"},
    {"name":"therocktrading","display_name":"The Rock Trading"},
    {"name":"bitstamp-ripple-gateway","display_name":"Bitstamp (Ripple Gateway)"},
    {"name":"altcoin-trader","display_name":"Altcoin Trader"},
    {"name":"waves-dex","display_name":"Waves Decentralized Exchange"},
    {"name":"koineks","display_name":"Koineks"},
    {"name":"ripple-china","display_name":"Ripple China"},
    {"name":"openledger","display_name":"OpenLedger DEX"},
    {"name":"bitcointrade","display_name":"BitcoinTrade"},
    {"name":"bitgrail","display_name":"BitGrail"},
    {"name":"coinut","display_name":"Coinut"},
    {"name":"tidebit","display_name":"Tidebit"},
    {"name":"lykke-exchange","display_name":"Lykke Exchange"},
    {"name":"c-cex","display_name":"C-CEX"},
    {"name":"bitcointoyou","display_name":"BitcoinToYou"},
    {"name":"coinrail","display_name":"Coinrail"},
    {"name":"localtrade","display_name":"LocalTrade"},
    {"name":"fargobase","display_name":"Fargobase"},
    {"name":"abucoins","display_name":"Abucoins"},
    {"name":"mr_ripple","display_name":"Mr. Ripple"},
    {"name":"bit2c","display_name":"Bit2C"},
    {"name":"coinsmarkets","display_name":"CoinsMarkets"},
    {"name":"hypex","display_name":"Hypex"},
    {"name":"tdax","display_name":"TDAX"},
    {"name":"coinmate","display_name":"CoinMate"},
    {"name":"bancor-network","display_name":"Bancor Network"},
    {"name":"surbtc","display_name":"SurBTC"},
    {"name":"coinroom","display_name":"Coinroom"},
    {"name":"c2cx","display_name":"C2CX"},
    {"name":"bitsane","display_name":"Bitsane"},
    {"name":"bittylicious","display_name":"Bittylicious"},
    {"name":"qryptos","display_name":"Qryptos"},
    {"name":"nevbit","display_name":"Nevbit"},
    {"name":"tcc-exchange","display_name":"TCC Exchange"},
    {"name":"kuna","display_name":"Kuna"},
    {"name":"braziliex","display_name":"Braziliex"},
    {"name":"coss","display_name":"COSS"},
    {"name":"bitex-la","display_name":"Bitex.la"},
    {"name":"cryptobridge","display_name":"CryptoBridge"},
    {"name":"triple-dice-exchange","display_name":"Tripe Dice Exchange"},
    {"name":"tux-exchange","display_name":"Tux Exchange"},
    {"name":"bleutrade","display_name":"Bleutrade"},
    {"name":"bitlish","display_name":"Bitlish"},
    {"name":"infinitycoin-exchange","display_name":"InfinityCoin Exchange"},
    {"name":"stocks-exchange","display_name":"Stocks.Exchange"},
    {"name":"bitflip","display_name":"BitFlip"},
    {"name":"stellar-decentralized-exchange","display_name":"Stellar Decentralized Exchange"},
    {"name":"ethexindia","display_name":"ETHEXIndia"},
    {"name":"nocks","display_name":"Nocks"},
    {"name":"coinrate","display_name":"Coinrate"},
    {"name":"novaexchange","display_name":"Novaexchange"},
    {"name":"ezbtc","display_name":"ezBtc"},
    {"name":"lbank","display_name":"Lbank"},
    {"name":"bcex","display_name":"BCEX"},
    {"name":"oex","display_name":"OEX"},
    {"name":"bitkonan","display_name":"BitKonan"},
    {"name":"trade-satoshi","display_name":"Trade Satoshi"},
    {"name":"cryptomate","display_name":"Cryptomate"},
    {"name":"bisq","display_name":"Bisq"},
    {"name":"nxt-asset-exchange","display_name":"Nxt Asset Exchange"},
    {"name":"decentrex","display_name":"Decentrex"},
    {"name":"bitmaszyna","display_name":"Bitmaszyna"},
    {"name":"btc-trade-ua","display_name":"BTC Trade UA"},
    {"name":"rippex","display_name":"Rippex"},
    {"name":"idex","display_name":"IDEX"},
    {"name":"cryptomarket","display_name":"CryptoMarket"},
    {"name":"southxchange","display_name":"SouthXchange"},
    {"name":"alcurex","display_name":"alcurEX"},
    {"name":"cryptox","display_name":"Cryptox"},
    {"name":"coingi","display_name":"Coingi"},
    {"name":"guldentrader","display_name":"GuldenTrader"},
    {"name":"okcoin-cn","display_name":"OKCoin.cn"},
    {"name":"counterparty-dex","display_name":"Counterparty DEX"},
    {"name":"dgtmarket","display_name":"Dgtmarket"},
    {"name":"isx","display_name":"ISX"},
    {"name":"heat-wallet","display_name":"Heat Wallet"},
    {"name":"freiexchange","display_name":"FreiExchange"},
    {"name":"ore-bz","display_name":"Ore.Bz"},
    {"name":"cryptoderivatives","display_name":"CryptoDerivatives"},
    {"name":"dc-ex","display_name":"DC-Ex"},
    {"name":"burst-asset-exchange","display_name":"Burst Asset Exchange"},
    {"name":"nix-e","display_name":"NIX-E"},
    {"name":"coincorner","display_name":"CoinCorner"},
    {"name":"omni-dex","display_name":"Omni DEX"},
    {"name":"leoxchange","display_name":"LEOxChange"},
    {"name":"excambriorex","display_name":"ExcambrioRex"},
    {"name":"virtacoinworld","display_name":"VirtacoinWorld"},
    {"name":"aidos-market","display_name":"AidosMarket"}]

conn = psycopg2.connect('dbname=coinspiracy user=batman')
cur = conn.cursor()

for data in exchange_data:
    print (data["name"])
    cur.execute("""
        INSERT INTO exchange (name, display_name)
        VALUES (%s, %s)
        """, (data["name"], data["display_name"]))


conn.commit()
cur.close()
conn.close()

