import psycopg2

currency_data = [{"tokens": ["Bitcoin", "BTC"], "symbol": "BTC", "name": "Bitcoin", "rank": 1, "slug": "bitcoin"},
     {"tokens": ["Ethereum", "ETH"], "symbol": "ETH", "name": "Ethereum", "rank": 2, "slug": "ethereum"},
     {"tokens": ["Bitcoin Cash", "BCH"], "symbol": "BCH", "name": "Bitcoin Cash", "rank": 3, "slug": "bitcoin-cash"},
     {"tokens": ["Ripple", "XRP"], "symbol": "XRP", "name": "Ripple", "rank": 4, "slug": "ripple"},
     {"tokens": ["Litecoin", "LTC"], "symbol": "LTC", "name": "Litecoin", "rank": 5, "slug": "litecoin"},
     {"tokens": ["IOTA", "MIOTA"], "symbol": "MIOTA", "name": "IOTA", "rank": 6, "slug": "iota"},
     {"tokens": ["Dash", "DASH"], "symbol": "DASH", "name": "Dash", "rank": 7, "slug": "dash"},
     {"tokens": ["Cardano", "ADA"], "symbol": "ADA", "name": "Cardano", "rank": 8, "slug": "cardano"},
     {"tokens": ["NEM", "XEM"], "symbol": "XEM", "name": "NEM", "rank": 9, "slug": "nem"},
     {"tokens": ["Bitcoin Gold", "BTG"], "symbol": "BTG", "name": "Bitcoin Gold", "rank": 10, "slug": "bitcoin-gold"},
     {"tokens": ["Monero", "XMR"], "symbol": "XMR", "name": "Monero", "rank": 11, "slug": "monero"},
     {"tokens": ["EOS", "EOS"], "symbol": "EOS", "name": "EOS", "rank": 12, "slug": "eos"},
     {"tokens": ["Stellar", "XLM"], "symbol": "XLM", "name": "Stellar", "rank": 13, "slug": "stellar"},
     {"tokens": ["NEO", "NEO"], "symbol": "NEO", "name": "NEO", "rank": 14, "slug": "neo"},
     {"tokens": ["Ethereum Classic", "ETC"], "symbol": "ETC", "name": "Ethereum Classic", "rank": 15, "slug": "ethereum-classic"},
     {"tokens": ["Qtum", "QTUM"], "symbol": "QTUM", "name": "Qtum", "rank": 16, "slug": "qtum"},
     {"tokens": ["Populous", "PPT"], "symbol": "PPT", "name": "Populous", "rank": 17, "slug": "populous"},
     {"tokens": ["BitConnect", "BCC"], "symbol": "BCC", "name": "BitConnect", "rank": 18, "slug": "bitconnect"},
     {"tokens": ["OmiseGO", "OMG"], "symbol": "OMG", "name": "OmiseGO", "rank": 19, "slug": "omisego"},
     {"tokens": ["Zcash", "ZEC"], "symbol": "ZEC", "name": "Zcash", "rank": 20, "slug": "zcash"},
     {"tokens": ["Waves", "WAVES"], "symbol": "WAVES", "name": "Waves", "rank": 21, "slug": "waves"},
     {"tokens": ["TRON", "TRX"], "symbol": "TRX", "name": "TRON", "rank": 22, "slug": "tron"},
     {"tokens": ["Lisk", "LSK"], "symbol": "LSK", "name": "Lisk", "rank": 23, "slug": "lisk"},
     {"tokens": ["Tether", "USDT"], "symbol": "USDT", "name": "Tether", "rank": 24, "slug": "tether"},
     {"tokens": ["Stratis", "STRAT"], "symbol": "STRAT", "name": "Stratis", "rank": 25, "slug": "stratis"},
     {"tokens": ["BitShares", "BTS"], "symbol": "BTS", "name": "BitShares", "rank": 26, "slug": "bitshares"},
     {"tokens": ["Hshare", "HSR"], "symbol": "HSR", "name": "Hshare", "rank": 27, "slug": "hshare"},
     {"tokens": ["Ardor", "ARDR"], "symbol": "ARDR", "name": "Ardor", "rank": 28, "slug": "ardor"},
     {"tokens": ["MonaCoin", "MONA"], "symbol": "MONA", "name": "MonaCoin", "rank": 29, "slug": "monacoin"},
     {"tokens": ["Nxt", "NXT"], "symbol": "NXT", "name": "Nxt", "rank": 30, "slug": "nxt"},
     {"tokens": ["Veritaseum", "VERI"], "symbol": "VERI", "name": "Veritaseum", "rank": 31, "slug": "veritaseum"},
     {"tokens": ["Bytecoin", "BCN"], "symbol": "BCN", "name": "Bytecoin", "rank": 32, "slug": "bytecoin-bcn"},
     {"tokens": ["Steem", "STEEM"], "symbol": "STEEM", "name": "Steem", "rank": 33, "slug": "steem"},
     {"tokens": ["Komodo", "KMD"], "symbol": "KMD", "name": "Komodo", "rank": 34, "slug": "komodo"},
     {"tokens": ["SALT", "SALT"], "symbol": "SALT", "name": "SALT", "rank": 35, "slug": "salt"},
     {"tokens": ["Decred", "DCR"], "symbol": "DCR", "name": "Decred", "rank": 36, "slug": "decred"},
     {"tokens": ["Ark", "ARK"], "symbol": "ARK", "name": "Ark", "rank": 37, "slug": "ark"},
     {"tokens": ["Binance Coin", "BNB"], "symbol": "BNB", "name": "Binance Coin", "rank": 38, "slug": "binance-coin"},
     {"tokens": ["Dogecoin", "DOGE"], "symbol": "DOGE", "name": "Dogecoin", "rank": 39, "slug": "dogecoin"},
     {"tokens": ["Augur", "REP"], "symbol": "REP", "name": "Augur", "rank": 40, "slug": "augur"},
     {"tokens": ["Einsteinium", "EMC2"], "symbol": "EMC2", "name": "Einsteinium", "rank": 41, "slug": "einsteinium"},
     {"tokens": ["RaiBlocks", "XRB"], "symbol": "XRB", "name": "RaiBlocks", "rank": 42, "slug": "raiblocks"},
     {"tokens": ["Electroneum", "ETN"], "symbol": "ETN", "name": "Electroneum", "rank": 43, "slug": "electroneum"},
     {"tokens": ["Vertcoin", "VTC"], "symbol": "VTC", "name": "Vertcoin", "rank": 44, "slug": "vertcoin"},
     {"tokens": ["Status", "SNT"], "symbol": "SNT", "name": "Status", "rank": 45, "slug": "status"},
     {"tokens": ["Golem", "GNT"], "symbol": "GNT", "name": "Golem", "rank": 46, "slug": "golem-network-tokens"},
     {"tokens": ["Siacoin", "SC"], "symbol": "SC", "name": "Siacoin", "rank": 47, "slug": "siacoin"},
     {"tokens": ["PIVX", "PIVX"], "symbol": "PIVX", "name": "PIVX", "rank": 48, "slug": "pivx"},
     {"tokens": ["Aeternity", "AE"], "symbol": "AE", "name": "Aeternity", "rank": 49, "slug": "aeternity"},
     {"tokens": ["DigixDAO", "DGD"], "symbol": "DGD", "name": "DigixDAO", "rank": 50, "slug": "digixdao"},
     {"tokens": ["Factom", "FCT"], "symbol": "FCT", "name": "Factom", "rank": 51, "slug": "factom"},
     {"tokens": ["Verge", "XVG"], "symbol": "XVG", "name": "Verge", "rank": 52, "slug": "verge"},
     {"tokens": ["TenX", "PAY"], "symbol": "PAY", "name": "TenX", "rank": 53, "slug": "tenx"},
     {"tokens": ["MaidSafeCoin", "MAID"], "symbol": "MAID", "name": "MaidSafeCoin", "rank": 54, "slug": "maidsafecoin"},
     {"tokens": ["QASH", "QASH"], "symbol": "QASH", "name": "QASH", "rank": 55, "slug": "qash"},
     {"tokens": ["Santiment Network Token", "SAN"], "symbol": "SAN", "name": "Santiment Network Token", "rank": 56, "slug": "santiment"},
     {"tokens": ["Bytom", "BTM"], "symbol": "BTM", "name": "Bytom", "rank": 57, "slug": "bytom"},
     {"tokens": ["Basic Attention Token", "BAT"], "symbol": "BAT", "name": "Basic Attention Token", "rank": 58, "slug": "basic-attention-token"},
     {"tokens": ["Power Ledger", "POWR"], "symbol": "POWR", "name": "Power Ledger", "rank": 59, "slug": "power-ledger"},
     {"tokens": ["Decentraland", "MANA"], "symbol": "MANA", "name": "Decentraland", "rank": 60, "slug": "decentraland"},
     {"tokens": ["Syscoin", "SYS"], "symbol": "SYS", "name": "Syscoin", "rank": 61, "slug": "syscoin"},
     {"tokens": ["Kyber Network", "KNC"], "symbol": "KNC", "name": "Kyber Network", "rank": 62, "slug": "kyber-network"},
     {"tokens": ["VeChain", "VEN"], "symbol": "VEN", "name": "VeChain", "rank": 63, "slug": "vechain"},
     {"tokens": ["Byteball Bytes", "GBYTE"], "symbol": "GBYTE", "name": "Byteball Bytes", "rank": 64, "slug": "byteball"},
     {"tokens": ["ZCoin", "XZC"], "symbol": "XZC", "name": "ZCoin", "rank": 65, "slug": "zcoin"},
     {"tokens": ["Walton", "WTC"], "symbol": "WTC", "name": "Walton", "rank": 66, "slug": "walton"},
     {"tokens": ["BitcoinDark", "BTCD"], "symbol": "BTCD", "name": "BitcoinDark", "rank": 67, "slug": "bitcoindark"},
     {"tokens": ["Gas", "GAS"], "symbol": "GAS", "name": "Gas", "rank": 68, "slug": "gas"},
     {"tokens": ["Streamr DATAcoin", "DATA"], "symbol": "DATA", "name": "Streamr DATAcoin", "rank": 69, "slug": "streamr-datacoin"},
     {"tokens": ["Nexus", "NXS"], "symbol": "NXS", "name": "Nexus", "rank": 70, "slug": "nexus"},
     {"tokens": ["Gnosis", "GNO"], "symbol": "GNO", "name": "Gnosis", "rank": 71, "slug": "gnosis-gno"},
     {"tokens": ["Cryptonex", "CNX"], "symbol": "CNX", "name": "Cryptonex", "rank": 72, "slug": "cryptonex"},
     {"tokens": ["DigiByte", "DGB"], "symbol": "DGB", "name": "DigiByte", "rank": 73, "slug": "digibyte"},
     {"tokens": ["0x", "ZRX"], "symbol": "ZRX", "name": "0x", "rank": 74, "slug": "0x"},
     {"tokens": ["Raiden Network Token", "RDN"], "symbol": "RDN", "name": "Raiden Network Token", "rank": 75, "slug": "raiden-network-token"},
     {"tokens": ["FunFair", "FUN"], "symbol": "FUN", "name": "FunFair", "rank": 76, "slug": "funfair"},
     {"tokens": ["Monaco", "MCO"], "symbol": "MCO", "name": "Monaco", "rank": 77, "slug": "monaco"},
     {"tokens": ["Iconomi", "ICN"], "symbol": "ICN", "name": "Iconomi", "rank": 78, "slug": "iconomi"},
     {"tokens": ["Request Network", "REQ"], "symbol": "REQ", "name": "Request Network", "rank": 79, "slug": "request-network"},
     {"tokens": ["GameCredits", "GAME"], "symbol": "GAME", "name": "GameCredits", "rank": 80, "slug": "gamecredits"},
     {"tokens": ["GXShares", "GXS"], "symbol": "GXS", "name": "GXShares", "rank": 81, "slug": "gxshares"},
     {"tokens": ["Bancor", "BNT"], "symbol": "BNT", "name": "Bancor", "rank": 82, "slug": "bancor"},
     {"tokens": ["Civic", "CVC"], "symbol": "CVC", "name": "Civic", "rank": 83, "slug": "civic"},
     {"tokens": ["NAV Coin", "NAV"], "symbol": "NAV", "name": "NAV Coin", "rank": 84, "slug": "nav-coin"},
     {"tokens": ["Aion", "AION"], "symbol": "AION", "name": "Aion", "rank": 85, "slug": "aion"},
     {"tokens": ["Pura", "PURA"], "symbol": "PURA", "name": "Pura", "rank": 86, "slug": "pura"},
     {"tokens": ["Metaverse ETP", "ETP"], "symbol": "ETP", "name": "Metaverse ETP", "rank": 87, "slug": "metaverse"},
     {"tokens": ["Metal", "MTL"], "symbol": "MTL", "name": "Metal", "rank": 88, "slug": "metal"},
     {"tokens": ["Blocknet", "BLOCK"], "symbol": "BLOCK", "name": "Blocknet", "rank": 89, "slug": "blocknet"},
     {"tokens": ["Revain", "R"], "symbol": "R", "name": "Revain", "rank": 90, "slug": "revain"},
     {"tokens": ["Edgeless", "EDG"], "symbol": "EDG", "name": "Edgeless", "rank": 91, "slug": "edgeless"},
     {"tokens": ["PayPie", "PPP"], "symbol": "PPP", "name": "PayPie", "rank": 92, "slug": "paypie"},
     {"tokens": ["Storj", "STORJ"], "symbol": "STORJ", "name": "Storj", "rank": 93, "slug": "storj"},
     {"tokens": ["RChain", "RHOC"], "symbol": "RHOC", "name": "RChain", "rank": 94, "slug": "rchain"},
     {"tokens": ["Time New Bank", "TNB"], "symbol": "TNB", "name": "Time New Bank", "rank": 95, "slug": "time-new-bank"},
     {"tokens": ["Ethos", "ETHOS"], "symbol": "ETHOS", "name": "Ethos", "rank": 96, "slug": "ethos"},
     {"tokens": ["Ubiq", "UBQ"], "symbol": "UBQ", "name": "Ubiq", "rank": 97, "slug": "ubiq"},
     {"tokens": ["ChainLink", "LINK"], "symbol": "LINK", "name": "ChainLink", "rank": 98, "slug": "chainlink"},
     {"tokens": ["Peercoin", "PPC"], "symbol": "PPC", "name": "Peercoin", "rank": 99, "slug": "peercoin"},
     {"tokens": ["Dragonchain", "DRGN"], "symbol": "DRGN", "name": "Dragonchain", "rank": 100, "slug": "dragonchain"},
     {"tokens": ["Substratum", "SUB"], "symbol": "SUB", "name": "Substratum", "rank": 101, "slug": "substratum"},
     {"tokens": ["MinexCoin", "MNX"], "symbol": "MNX", "name": "MinexCoin", "rank": 102, "slug": "minexcoin"},
     {"tokens": ["SmartCash", "SMART"], "symbol": "SMART", "name": "SmartCash", "rank": 103, "slug": "smartcash"},
     {"tokens": ["Ink", "INK"], "symbol": "INK", "name": "Ink", "rank": 104, "slug": "ink"},
     {"tokens": ["Cobinhood", "COB"], "symbol": "COB", "name": "Cobinhood", "rank": 105, "slug": "cobinhood"},
     {"tokens": ["SingularDTV", "SNGLS"], "symbol": "SNGLS", "name": "SingularDTV", "rank": 106, "slug": "singulardtv"},
     {"tokens": ["BitBay", "BAY"], "symbol": "BAY", "name": "BitBay", "rank": 107, "slug": "bitbay"},
     {"tokens": ["ZenCash", "ZEN"], "symbol": "ZEN", "name": "ZenCash", "rank": 108, "slug": "zencash"},
     {"tokens": ["Groestlcoin", "GRS"], "symbol": "GRS", "name": "Groestlcoin", "rank": 109, "slug": "groestlcoin"},
     {"tokens": ["Skycoin", "SKY"], "symbol": "SKY", "name": "Skycoin", "rank": 110, "slug": "skycoin"},
     {"tokens": ["SONM", "SNM"], "symbol": "SNM", "name": "SONM", "rank": 111, "slug": "sonm"},
     {"tokens": ["Aragon", "ANT"], "symbol": "ANT", "name": "Aragon", "rank": 112, "slug": "aragon"},
     {"tokens": ["Achain", "ACT"], "symbol": "ACT", "name": "Achain", "rank": 113, "slug": "achain"},
     {"tokens": ["AdEx", "ADX"], "symbol": "ADX", "name": "AdEx", "rank": 114, "slug": "adx-net"},
     {"tokens": ["Quantstamp", "QSP"], "symbol": "QSP", "name": "Quantstamp", "rank": 115, "slug": "quantstamp"},
     {"tokens": ["Feathercoin", "FTC"], "symbol": "FTC", "name": "Feathercoin", "rank": 116, "slug": "feathercoin"},
     {"tokens": ["Ripio Credit Network", "RCN"], "symbol": "RCN", "name": "Ripio Credit Network", "rank": 117, "slug": "ripio-credit-network"},
     {"tokens": ["Humaniq", "HMQ"], "symbol": "HMQ", "name": "Humaniq", "rank": 118, "slug": "humaniq"},
     {"tokens": ["Asch", "XAS"], "symbol": "XAS", "name": "Asch", "rank": 119, "slug": "asch"},
     {"tokens": ["Lykke", "LKK"], "symbol": "LKK", "name": "Lykke", "rank": 120, "slug": "lykke"},
     {"tokens": ["Loopring", "LRC"], "symbol": "LRC", "name": "Loopring", "rank": 121, "slug": "loopring"},
     {"tokens": ["Particl", "PART"], "symbol": "PART", "name": "Particl", "rank": 122, "slug": "particl"},
     {"tokens": ["Quantum Resistant Ledger", "QRL"], "symbol": "QRL", "name": "Quantum Resistant Ledger", "rank": 123, "slug": "quantum-resistant-ledger"},
     {"tokens": ["Counterparty", "XCP"], "symbol": "XCP", "name": "Counterparty", "rank": 124, "slug": "counterparty"},
     {"tokens": ["YOYOW", "YOYOW"], "symbol": "YOYOW", "name": "YOYOW", "rank": 125, "slug": "yoyow"},
     {"tokens": ["PotCoin", "POT"], "symbol": "POT", "name": "PotCoin", "rank": 126, "slug": "potcoin"},
     {"tokens": ["ATMChain", "ATM"], "symbol": "ATM", "name": "ATMChain", "rank": 127, "slug": "attention-token-of-media"},
     {"tokens": ["Voxels", "VOX"], "symbol": "VOX", "name": "Voxels", "rank": 128, "slug": "voxels"},
     {"tokens": ["Rise", "RISE"], "symbol": "RISE", "name": "Rise", "rank": 129, "slug": "rise"},
     {"tokens": ["Pepe Cash", "PEPECASH"], "symbol": "PEPECASH", "name": "Pepe Cash", "rank": 130, "slug": "pepe-cash"},
     {"tokens": ["FairCoin", "FAIR"], "symbol": "FAIR", "name": "FairCoin", "rank": 131, "slug": "faircoin"},
     {"tokens": ["Mercury", "MER"], "symbol": "MER", "name": "Mercury", "rank": 132, "slug": "mercury"},
     {"tokens": ["Viacoin", "VIA"], "symbol": "VIA", "name": "Viacoin", "rank": 133, "slug": "viacoin"},
     {"tokens": ["MobileGo", "MGO"], "symbol": "MGO", "name": "MobileGo", "rank": 134, "slug": "mobilego"},
     {"tokens": ["Eidoo", "EDO"], "symbol": "EDO", "name": "Eidoo", "rank": 135, "slug": "eidoo"},
     {"tokens": ["iExec RLC", "RLC"], "symbol": "RLC", "name": "iExec RLC", "rank": 136, "slug": "rlc"},
     {"tokens": ["WaBi", "WABI"], "symbol": "WABI", "name": "WaBi", "rank": 137, "slug": "wabi"},
     {"tokens": ["Namecoin", "NMC"], "symbol": "NMC", "name": "Namecoin", "rank": 138, "slug": "namecoin"},
     {"tokens": ["Safe Exchange Coin", "SAFEX"], "symbol": "SAFEX", "name": "Safe Exchange Coin", "rank": 139, "slug": "safe-exchange-coin"}]

conn = psycopg2.connect('dbname=coinspiracy user=batman')
cur = conn.cursor()

for data in currency_data:
    print (data["symbol"])
    cur.execute("""
        INSERT INTO currency (symbol, display_name, slug)
        VALUES (%s, %s, %s)
        """, (data["symbol"], data["name"], data["slug"]))

conn.commit()
cur.close()
conn.close()